[2019-12-12 04:24:28 +0000] [25710] [INFO] Starting gunicorn 20.0.4
[2019-12-12 04:24:28 +0000] [25710] [INFO] Listening at: http://127.0.0.1:8000 (25710)
[2019-12-12 04:24:28 +0000] [25710] [INFO] Using worker: sync
[2019-12-12 04:24:28 +0000] [25715] [INFO] Booting worker with pid: 25715
[2019-12-12 04:24:28 +0000] [25716] [INFO] Booting worker with pid: 25716
[2019-12-12 04:24:28 +0000] [25715] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 8
    from async import do_async
             ^
SyntaxError: invalid syntax
[2019-12-12 04:24:28 +0000] [25715] [INFO] Worker exiting (pid: 25715)
[2019-12-12 04:24:28 +0000] [25717] [INFO] Booting worker with pid: 25717
[2019-12-12 04:24:28 +0000] [25716] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 8
    from async import do_async
             ^
SyntaxError: invalid syntax
[2019-12-12 04:24:28 +0000] [25716] [INFO] Worker exiting (pid: 25716)
[2019-12-12 04:24:28 +0000] [25717] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 8
    from async import do_async
             ^
SyntaxError: invalid syntax
[2019-12-12 04:24:28 +0000] [25717] [INFO] Worker exiting (pid: 25717)
[2019-12-12 04:24:30 +0000] [25710] [INFO] Shutting down: Master
[2019-12-12 04:24:30 +0000] [25710] [INFO] Reason: Worker failed to boot.
Traceback (most recent call last):
  File "/opt/gongenv/bin/gunicorn", line 5, in <module>
    from gunicorn.app.wsgiapp import run
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 9, in <module>
    from gunicorn.app.base import Application
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 11, in <module>
    from gunicorn import util
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 7, in <module>
    import email.utils
  File "/usr/lib/python3.7/email/utils.py", line 33, in <module>
    from email._parseaddr import quote
  File "/usr/lib/python3.7/email/_parseaddr.py", line 16, in <module>
    import time, calendar
  File "/usr/lib/python3.7/calendar.py", line 24, in <module>
    class IllegalMonthError(ValueError):
  File "/usr/lib/python3.7/calendar.py", line 24, in IllegalMonthError
    class IllegalMonthError(ValueError):
KeyboardInterrupt
[2019-12-12 04:47:07 +0000] [28710] [INFO] Starting gunicorn 20.0.4
[2019-12-12 04:47:07 +0000] [28710] [INFO] Listening at: http://127.0.0.1:8000 (28710)
[2019-12-12 04:47:07 +0000] [28710] [INFO] Using worker: sync
[2019-12-12 04:47:07 +0000] [28738] [INFO] Booting worker with pid: 28738
[2019-12-12 04:47:08 +0000] [28739] [INFO] Booting worker with pid: 28739
[2019-12-12 04:47:08 +0000] [28740] [INFO] Booting worker with pid: 28740
[2019-12-12 04:47:08 +0000] [28738] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 8
    from async import do_async
             ^
SyntaxError: invalid syntax
[2019-12-12 04:47:08 +0000] [28738] [INFO] Worker exiting (pid: 28738)
[2019-12-12 04:47:08 +0000] [28739] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 8
    from async import do_async
             ^
SyntaxError: invalid syntax
[2019-12-12 04:47:08 +0000] [28739] [INFO] Worker exiting (pid: 28739)
[2019-12-12 04:47:08 +0000] [28740] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 8
    from async import do_async
             ^
SyntaxError: invalid syntax
[2019-12-12 04:47:08 +0000] [28740] [INFO] Worker exiting (pid: 28740)
[2019-12-12 04:47:11 +0000] [28710] [INFO] Shutting down: Master
[2019-12-12 04:47:11 +0000] [28710] [INFO] Reason: Worker failed to boot.
[2019-12-12 04:52:31 +0000] [29656] [INFO] Starting gunicorn 20.0.4
[2019-12-12 04:52:31 +0000] [29656] [INFO] Listening at: http://127.0.0.1:8000 (29656)
[2019-12-12 04:52:31 +0000] [29656] [INFO] Using worker: sync
[2019-12-12 04:52:31 +0000] [29677] [INFO] Booting worker with pid: 29677
[2019-12-12 04:52:31 +0000] [29678] [INFO] Booting worker with pid: 29678
[2019-12-12 04:52:31 +0000] [29682] [INFO] Booting worker with pid: 29682
[2019-12-12 04:52:31 +0000] [29677] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 22
    print 'Initializing gong database'
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Initializing gong database')?
[2019-12-12 04:52:31 +0000] [29677] [INFO] Worker exiting (pid: 29677)
[2019-12-12 04:52:31 +0000] [29678] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 22
    print 'Initializing gong database'
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Initializing gong database')?
[2019-12-12 04:52:32 +0000] [29678] [INFO] Worker exiting (pid: 29678)
[2019-12-12 04:52:31 +0000] [29682] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
  File "/opt/gong/gong.py", line 22
    print 'Initializing gong database'
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Initializing gong database')?
[2019-12-12 04:52:32 +0000] [29682] [INFO] Worker exiting (pid: 29682)
[2019-12-12 04:52:33 +0000] [29656] [INFO] Shutting down: Master
[2019-12-12 04:52:33 +0000] [29656] [INFO] Reason: Worker failed to boot.
[2019-12-12 04:54:22 +0000] [29967] [INFO] Starting gunicorn 20.0.4
[2019-12-12 04:54:22 +0000] [29967] [INFO] Listening at: http://127.0.0.1:8000 (29967)
[2019-12-12 04:54:22 +0000] [29967] [INFO] Using worker: sync
[2019-12-12 04:54:22 +0000] [30008] [INFO] Booting worker with pid: 30008
[2019-12-12 04:54:22 +0000] [30014] [INFO] Booting worker with pid: 30014
[2019-12-12 04:54:22 +0000] [30015] [INFO] Booting worker with pid: 30015
[2019-12-12 04:54:38 +0000] [30008] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
ImportError: cannot import name 'init_gong' from 'gong' (/opt/gong/gong.py)
[2019-12-12 04:54:38 +0000] [30014] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
ImportError: cannot import name 'init_gong' from 'gong' (/opt/gong/gong.py)
[2019-12-12 04:54:38 +0000] [30008] [INFO] Worker exiting (pid: 30008)
[2019-12-12 04:54:38 +0000] [30014] [INFO] Worker exiting (pid: 30014)
[2019-12-12 04:54:38 +0000] [30015] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong import (init_gong, init_db, app, )
ImportError: cannot import name 'init_gong' from 'gong' (/opt/gong/gong.py)
[2019-12-12 04:54:39 +0000] [30015] [INFO] Worker exiting (pid: 30015)
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/gongenv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2019-12-12 05:17:39 +0000] [1502] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:17:39 +0000] [1502] [INFO] Listening at: http://127.0.0.1:8000 (1502)
[2019-12-12 05:17:39 +0000] [1502] [INFO] Using worker: sync
[2019-12-12 05:17:40 +0000] [1535] [INFO] Booting worker with pid: 1535
[2019-12-12 05:17:40 +0000] [1536] [INFO] Booting worker with pid: 1536
[2019-12-12 05:17:40 +0000] [1537] [INFO] Booting worker with pid: 1537
[2019-12-12 05:17:52 +0000] [1537] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:17:52 +0000] [1536] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:17:52 +0000] [1535] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:17:52 +0000] [1535] [INFO] Worker exiting (pid: 1535)
[2019-12-12 05:17:52 +0000] [1536] [INFO] Worker exiting (pid: 1536)
[2019-12-12 05:17:52 +0000] [1537] [INFO] Worker exiting (pid: 1537)
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/gongenv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 382, in stop
    sock.close_sockets(self.LISTENERS, unlink)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/sock.py", line 209, in close_sockets
    sock_name = sock.getsockname()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2019-12-12 05:20:02 +0000] [1914] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:20:02 +0000] [1914] [INFO] Listening at: http://127.0.0.1:8000 (1914)
[2019-12-12 05:20:02 +0000] [1914] [INFO] Using worker: sync
[2019-12-12 05:20:02 +0000] [1938] [INFO] Booting worker with pid: 1938
[2019-12-12 05:20:02 +0000] [1939] [INFO] Booting worker with pid: 1939
[2019-12-12 05:20:02 +0000] [1940] [INFO] Booting worker with pid: 1940
[2019-12-12 05:20:13 +0000] [1939] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:20:13 +0000] [1939] [INFO] Worker exiting (pid: 1939)
[2019-12-12 05:20:13 +0000] [1938] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:20:13 +0000] [1938] [INFO] Worker exiting (pid: 1938)
[2019-12-12 05:20:13 +0000] [1940] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:20:13 +0000] [1940] [INFO] Worker exiting (pid: 1940)
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
    self.sleep()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
    ready = select.select([self.PIPE[0]], [], [], 1.0)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/gongenv/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
    self.stop()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 388, in stop
    limit = time.time() + self.cfg.graceful_timeout
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/config.py", line 55, in __getattr__
    if name not in self.settings:
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
[2019-12-12 05:21:20 +0000] [2127] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:21:20 +0000] [2127] [INFO] Listening at: http://127.0.0.1:8000 (2127)
[2019-12-12 05:21:20 +0000] [2127] [INFO] Using worker: sync
[2019-12-12 05:21:20 +0000] [2148] [INFO] Booting worker with pid: 2148
[2019-12-12 05:21:20 +0000] [2149] [INFO] Booting worker with pid: 2149
[2019-12-12 05:21:21 +0000] [2150] [INFO] Booting worker with pid: 2150
[2019-12-12 05:21:31 +0000] [2148] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:21:32 +0000] [2148] [INFO] Worker exiting (pid: 2148)
[2019-12-12 05:21:31 +0000] [2149] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:21:32 +0000] [2149] [INFO] Worker exiting (pid: 2149)
[2019-12-12 05:21:32 +0000] [2150] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:21:32 +0000] [2150] [INFO] Worker exiting (pid: 2150)
[2019-12-12 05:21:34 +0000] [2127] [INFO] Shutting down: Master
[2019-12-12 05:21:34 +0000] [2127] [INFO] Reason: Worker failed to boot.
[2019-12-12 05:22:33 +0000] [2402] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:22:33 +0000] [2402] [INFO] Listening at: http://127.0.0.1:8000 (2402)
[2019-12-12 05:22:33 +0000] [2402] [INFO] Using worker: sync
[2019-12-12 05:22:33 +0000] [2422] [INFO] Booting worker with pid: 2422
[2019-12-12 05:22:34 +0000] [2423] [INFO] Booting worker with pid: 2423
[2019-12-12 05:22:34 +0000] [2424] [INFO] Booting worker with pid: 2424
[2019-12-12 05:22:44 +0000] [2422] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:22:45 +0000] [2422] [INFO] Worker exiting (pid: 2422)
[2019-12-12 05:22:45 +0000] [2423] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:22:45 +0000] [2423] [INFO] Worker exiting (pid: 2423)
[2019-12-12 05:22:45 +0000] [2424] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
  File "/opt/gong/gong.py", line 7, in <module>
    from gong.do_async import do_async
ModuleNotFoundError: No module named 'gong.do_async'; 'gong' is not a package
[2019-12-12 05:22:45 +0000] [2424] [INFO] Worker exiting (pid: 2424)
[2019-12-12 05:22:47 +0000] [2402] [INFO] Shutting down: Master
[2019-12-12 05:22:47 +0000] [2402] [INFO] Reason: Worker failed to boot.
[2019-12-12 05:25:04 +0000] [2831] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:25:04 +0000] [2831] [INFO] Listening at: http://127.0.0.1:8000 (2831)
[2019-12-12 05:25:04 +0000] [2831] [INFO] Using worker: sync
[2019-12-12 05:25:04 +0000] [2844] [INFO] Booting worker with pid: 2844
[2019-12-12 05:25:05 +0000] [2845] [INFO] Booting worker with pid: 2845
[2019-12-12 05:25:05 +0000] [2846] [INFO] Booting worker with pid: 2846
[2019-12-12 05:25:16 +0000] [2844] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
ModuleNotFoundError: No module named 'gong.gong'; 'gong' is not a package
[2019-12-12 05:25:16 +0000] [2844] [INFO] Worker exiting (pid: 2844)
[2019-12-12 05:25:16 +0000] [2845] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
ModuleNotFoundError: No module named 'gong.gong'; 'gong' is not a package
[2019-12-12 05:25:16 +0000] [2845] [INFO] Worker exiting (pid: 2845)
[2019-12-12 05:25:17 +0000] [2846] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/gong/wsgi.py", line 1, in <module>
    from gong.gong import (init_db, app, )
ModuleNotFoundError: No module named 'gong.gong'; 'gong' is not a package
[2019-12-12 05:25:17 +0000] [2846] [INFO] Worker exiting (pid: 2846)
[2019-12-12 05:25:18 +0000] [2831] [INFO] Shutting down: Master
[2019-12-12 05:25:18 +0000] [2831] [INFO] Reason: Worker failed to boot.
[2019-12-12 05:26:53 +0000] [3199] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:26:53 +0000] [3199] [INFO] Listening at: http://127.0.0.1:8000 (3199)
[2019-12-12 05:26:53 +0000] [3199] [INFO] Using worker: sync
[2019-12-12 05:26:53 +0000] [3219] [INFO] Booting worker with pid: 3219
[2019-12-12 05:26:53 +0000] [3220] [INFO] Booting worker with pid: 3220
[2019-12-12 05:26:54 +0000] [3221] [INFO] Booting worker with pid: 3221
[2019-12-12 05:27:25 +0000] [3199] [INFO] Handling signal: int
[2019-12-12 05:27:25 +0000] [3219] [INFO] Worker exiting (pid: 3219)
[2019-12-12 05:27:25 +0000] [3220] [INFO] Worker exiting (pid: 3220)
[2019-12-12 05:27:25 +0000] [3221] [INFO] Worker exiting (pid: 3221)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/gong/gong.py", line 40, in ring_gong
    pi.set_servo_pulsewidth(servo_pin, left_cycle)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 1647, in set_servo_pulsewidth
    self.sl, _PI_CMD_SERVO, user_gpio, int(pulsewidth)))
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 993, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'

                                                                [2019-12-12 05:33:07 +0000] [848] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:33:07 +0000] [848] [INFO] Listening at: http://127.0.0.1:8000 (848)
[2019-12-12 05:33:07 +0000] [848] [INFO] Using worker: sync
[2019-12-12 05:33:07 +0000] [881] [INFO] Booting worker with pid: 881
[2019-12-12 05:33:07 +0000] [882] [INFO] Booting worker with pid: 882
[2019-12-12 05:33:07 +0000] [883] [INFO] Booting worker with pid: 883
[2019-12-12 05:35:32 +0000] [882] [INFO] Worker exiting (pid: 882)
[2019-12-12 05:35:32 +0000] [883] [INFO] Worker exiting (pid: 883)
[2019-12-12 05:35:31 +0000] [881] [INFO] Worker exiting (pid: 881)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/gong/gong.py", line 40, in ring_gong
    pi.set_servo_pulsewidth(servo_pin, left_cycle)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 1647, in set_servo_pulsewidth
    self.sl, _PI_CMD_SERVO, user_gpio, int(pulsewidth)))
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 993, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/gong/gong.py", line 40, in ring_gong
    pi.set_servo_pulsewidth(servo_pin, left_cycle)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 1647, in set_servo_pulsewidth
    self.sl, _PI_CMD_SERVO, user_gpio, int(pulsewidth)))
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 993, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'

Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/gong/gong.py", line 40, in ring_gong
    pi.set_servo_pulsewidth(servo_pin, left_cycle)
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 1647, in set_servo_pulsewidth
    self.sl, _PI_CMD_SERVO, user_gpio, int(pulsewidth)))
  File "/home/pi/.virtualenvs/gong/lib/python3.7/site-packages/pigpio.py", line 993, in _pigpio_command
    sl.s.send(struct.pack('IIII', cmd, p1, p2, 0))
AttributeError: 'NoneType' object has no attribute 'send'

[2019-12-12 05:35:32 +0000] [848] [INFO] Handling signal: term
[2019-12-12 05:35:32 +0000] [848] [INFO] Shutting down: Master
[2019-12-12 05:35:44 +0000] [1421] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:35:44 +0000] [1421] [INFO] Listening at: http://127.0.0.1:8000 (1421)
[2019-12-12 05:35:44 +0000] [1421] [INFO] Using worker: sync
[2019-12-12 05:35:44 +0000] [1489] [INFO] Booting worker with pid: 1489
[2019-12-12 05:35:44 +0000] [1491] [INFO] Booting worker with pid: 1491
[2019-12-12 05:35:44 +0000] [1493] [INFO] Booting worker with pid: 1493
[2019-12-12 05:42:21 +0000] [1421] [INFO] Handling signal: term
[2019-12-12 05:42:21 +0000] [1489] [INFO] Worker exiting (pid: 1489)
[2019-12-12 05:42:21 +0000] [1493] [INFO] Worker exiting (pid: 1493)
[2019-12-12 05:42:21 +0000] [1491] [INFO] Worker exiting (pid: 1491)
[2019-12-12 05:42:25 +0000] [1421] [INFO] Shutting down: Master
[2019-12-12 05:44:33 +0000] [232] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:44:33 +0000] [232] [INFO] Listening at: http://127.0.0.1:8000 (232)
[2019-12-12 05:44:33 +0000] [232] [INFO] Using worker: sync
[2019-12-12 05:44:33 +0000] [441] [INFO] Booting worker with pid: 441
[2019-12-12 05:44:33 +0000] [442] [INFO] Booting worker with pid: 442
[2019-12-12 05:44:34 +0000] [443] [INFO] Booting worker with pid: 443
[2019-12-12 05:45:09 +0000] [232] [CRITICAL] WORKER TIMEOUT (pid:441)
[2019-12-12 05:45:09 +0000] [232] [CRITICAL] WORKER TIMEOUT (pid:442)
[2019-12-12 05:45:09 +0000] [232] [CRITICAL] WORKER TIMEOUT (pid:443)
[2019-12-12 05:45:09 +0000] [441] [INFO] Worker exiting (pid: 441)
[2019-12-12 05:45:09 +0000] [442] [INFO] Worker exiting (pid: 442)
[2019-12-12 05:45:09 +0000] [443] [INFO] Worker exiting (pid: 443)
[2019-12-12 05:45:10 +0000] [460] [INFO] Booting worker with pid: 460
[2019-12-12 05:45:10 +0000] [461] [INFO] Booting worker with pid: 461
[2019-12-12 05:45:10 +0000] [462] [INFO] Booting worker with pid: 462
[2019-12-12 05:45:40 +0000] [232] [CRITICAL] WORKER TIMEOUT (pid:460)
[2019-12-12 05:45:40 +0000] [232] [CRITICAL] WORKER TIMEOUT (pid:461)
[2019-12-12 05:45:40 +0000] [232] [CRITICAL] WORKER TIMEOUT (pid:462)
[2019-12-12 05:45:41 +0000] [460] [INFO] Worker exiting (pid: 460)
[2019-12-12 05:45:41 +0000] [461] [INFO] Worker exiting (pid: 461)
[2019-12-12 05:45:41 +0000] [462] [INFO] Worker exiting (pid: 462)
[2019-12-12 05:45:42 +0000] [585] [INFO] Booting worker with pid: 585
[2019-12-12 05:45:42 +0000] [586] [INFO] Booting worker with pid: 586
[2019-12-12 05:45:42 +0000] [587] [INFO] Booting worker with pid: 587
[2019-12-12 05:50:56 +0000] [232] [INFO] Handling signal: term
[2019-12-12 05:50:56 +0000] [585] [INFO] Worker exiting (pid: 585)
[2019-12-12 05:50:56 +0000] [587] [INFO] Worker exiting (pid: 587)
[2019-12-12 05:50:56 +0000] [586] [INFO] Worker exiting (pid: 586)
[2019-12-12 05:50:59 +0000] [232] [INFO] Shutting down: Master
[2019-12-12 05:55:27 +0000] [2670] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:55:27 +0000] [2670] [INFO] Listening at: http://127.0.0.1:8000 (2670)
[2019-12-12 05:55:27 +0000] [2670] [INFO] Using worker: sync
[2019-12-12 05:55:27 +0000] [2731] [INFO] Booting worker with pid: 2731
[2019-12-12 05:55:28 +0000] [2732] [INFO] Booting worker with pid: 2732
[2019-12-12 05:55:28 +0000] [2733] [INFO] Booting worker with pid: 2733
[2019-12-12 05:57:05 +0000] [2670] [INFO] Handling signal: term
[2019-12-12 05:57:05 +0000] [2732] [INFO] Worker exiting (pid: 2732)
[2019-12-12 05:57:05 +0000] [2731] [INFO] Worker exiting (pid: 2731)
[2019-12-12 05:57:05 +0000] [2733] [INFO] Worker exiting (pid: 2733)
[2019-12-12 05:57:12 +0000] [2670] [INFO] Shutting down: Master
[2019-12-12 05:57:53 +0000] [255] [INFO] Starting gunicorn 20.0.4
[2019-12-12 05:57:53 +0000] [255] [INFO] Listening at: http://127.0.0.1:8000 (255)
[2019-12-12 05:57:53 +0000] [255] [INFO] Using worker: sync
[2019-12-12 05:57:53 +0000] [440] [INFO] Booting worker with pid: 440
[2019-12-12 05:57:53 +0000] [441] [INFO] Booting worker with pid: 441
[2019-12-12 05:57:53 +0000] [442] [INFO] Booting worker with pid: 442
[2019-12-12 05:58:30 +0000] [255] [CRITICAL] WORKER TIMEOUT (pid:440)
[2019-12-12 05:58:30 +0000] [255] [CRITICAL] WORKER TIMEOUT (pid:441)
[2019-12-12 05:58:30 +0000] [255] [CRITICAL] WORKER TIMEOUT (pid:442)
[2019-12-12 05:58:30 +0000] [440] [INFO] Worker exiting (pid: 440)
[2019-12-12 05:58:30 +0000] [441] [INFO] Worker exiting (pid: 441)
[2019-12-12 05:58:31 +0000] [442] [INFO] Worker exiting (pid: 442)
[2019-12-12 05:58:32 +0000] [468] [INFO] Booting worker with pid: 468
[2019-12-12 05:58:32 +0000] [469] [INFO] Booting worker with pid: 469
[2019-12-12 05:58:32 +0000] [470] [INFO] Booting worker with pid: 470
[2019-12-12 06:06:35 +0000] [468] [INFO] Worker exiting (pid: 468)
[2019-12-12 06:06:35 +0000] [469] [INFO] Worker exiting (pid: 469)
[2019-12-12 06:06:35 +0000] [470] [INFO] Worker exiting (pid: 470)
[2019-12-12 06:06:35 +0000] [255] [INFO] Handling signal: term
[2019-12-12 06:06:37 +0000] [255] [INFO] Shutting down: Master
[2019-12-12 06:06:46 +0000] [1673] [INFO] Starting gunicorn 20.0.4
[2019-12-12 06:06:46 +0000] [1673] [INFO] Listening at: http://127.0.0.1:8000 (1673)
[2019-12-12 06:06:47 +0000] [1673] [INFO] Using worker: sync
[2019-12-12 06:06:47 +0000] [1703] [INFO] Booting worker with pid: 1703
[2019-12-12 06:06:47 +0000] [1704] [INFO] Booting worker with pid: 1704
[2019-12-12 06:06:47 +0000] [1705] [INFO] Booting worker with pid: 1705
[2019-12-12 06:07:28 +0000] [1673] [INFO] Handling signal: term
[2019-12-12 06:07:28 +0000] [1705] [INFO] Worker exiting (pid: 1705)
[2019-12-12 06:07:28 +0000] [1704] [INFO] Worker exiting (pid: 1704)
[2019-12-12 06:07:28 +0000] [1703] [INFO] Worker exiting (pid: 1703)
[2019-12-12 06:07:31 +0000] [1673] [INFO] Shutting down: Master
[2019-12-12 06:07:40 +0000] [1838] [INFO] Starting gunicorn 20.0.4
[2019-12-12 06:07:40 +0000] [1838] [INFO] Listening at: http://127.0.0.1:8000 (1838)
[2019-12-12 06:07:40 +0000] [1838] [INFO] Using worker: sync
[2019-12-12 06:07:40 +0000] [1861] [INFO] Booting worker with pid: 1861
[2019-12-12 06:07:40 +0000] [1862] [INFO] Booting worker with pid: 1862
[2019-12-12 06:07:40 +0000] [1863] [INFO] Booting worker with pid: 1863
